### ISSUE TITLE
hang on crash, widget 2.22

### ISSUE THREAD

**Issue by pjstorm** [cryptostorm/cstorm_widget#2]
From a member:

"When I Disconnect It always gives me a windows error. and it leaves my adapter with the gateway set to proxy not obtain auto"

Also report of Bitdefender being angry with the widget - some hints it's upset with script-y activities, which could be related to the firewall rulechains added by the webRTC leakblock syntax?

**Comment by df-cryptostorm** [comment]
It's possible. The WebRTC and IPv6 block, and the DNS leak fix are all accomplished using netsh.exe commands. I'm sure some malicious programs out there also use netsh.exe.

Best thing to do is add client.exe (and the batch [.bat] files in c:\program files (x86)\cryptostorm\user)
to your antivirus-like program's whitelist (some call it an exclusion list).
