### ISSUE TITLE
Windows widget going to 'not responding' on disconnect, not restoring settings correctly.

### ISSUE THREAD

**Issue by FTOtter** [cryptostorm/cstorm_widget#6]
Have been having this issue for a bit. When I disconnect a session, the widget 8/10 times 

hangs and eventually begins 'Not Responding'. I have to exit it with task manager, and then typically have to restart my computer afterwards as the widget doesn't finish setting my DNS back to normal. Even when the widget does seem to work normally upon shutdown and appears to have restored all of my settings, I have to restart my computer to visit any webpages as they will all result in "we're having trouble finding that site" type messages until I reboot.

I also have recently been getting the pop-up in the attached image when connecting recently, but I am unsure if it's related to the other issue or not. 
<img width="366" alt="crypto" src="https://user-images.githubusercontent.com/8353190/71783257-1880cd80-2fb2-11ea-9b91-434bb65817ef.png">

**Comment by df-cryptostorm** [comment]
This issue should be fixed by now, the DNS code was rewritten back in early 2021, and nobody seems to be seeing anymore crash-on-exit bugs.
