### ISSUE TITLE
Any Plan to Update the Client?

### ISSUE THREAD

**Issue by sr093906** [cryptostorm/cstorm_widget#7]
It seems the widget client hasn't been updated for about two years. As a result, many library and dependency files are now outdated and vulnerable. Do you plan to release new version of the software. I am a long-time customer.

**Comment by df-cryptostorm** [comment]
Updated now. The libraries/dependencies used by the old version don't have any known vulnerabilities that apply to the context they're used in, so clients who haven't upgraded yet are still secure (though they should upgrade anyways).
